optimize apply_net_colors
horizon-eda/horizon pull request #615
Opened 2021-10-08 17:17 UTC by rroohhh

If there are a lot of nets with custom colors, this was quite slow.

This currently only touches `apply_net_colors`, however `update_highlights` does some very similar operations, so it should be possible to build the `net_to_object_ref` map once and then use it for both.

2021-10-08 22:18 UTC, carrotIndustries commented on src/imp/imp_board.cpp
> +    for (const auto &it_track : core_board.get_board()->tracks) {
since you're touching that code, you might as well use structured bindings, also makes the following insertion look somwhat nicer.

`for (const auto &[uu, track] ...)`

2021-10-09 13:20 UTC, rroohhh commented on src/imp/imp_board.cpp
> +                .first->second.push_back(ObjectRef(ObjectType::TRACK, it_track.first));
Oh yeah, that makes much more sense.

2021-10-09 13:40 UTC, carrotIndustries requested changes

2021-10-09 13:40 UTC, carrotIndustries commented on src/imp/imp_board.cpp
> +        net_to_object_ref[track.net.uuid].emplace_back(ObjectRef(ObjectType::TRACK, uu));
```suggestion
        net_to_object_ref[track.net.uuid].emplace_back(ObjectType::TRACK, uu);
```

2021-10-09 13:40 UTC, carrotIndustries commented on src/imp/imp_board.cpp
> +        net_to_object_ref[via.junction->net.uuid].emplace_back(ObjectRef(ObjectType::VIA, uu));
```suggestion
        net_to_object_ref[via.junction->net.uuid].emplace_back(ObjectType::VIA, uu);
```

2021-10-09 13:40 UTC, carrotIndustries commented on src/imp/imp_board.cpp
> +            net_to_object_ref[pad.net.uuid].emplace_back(ObjectRef(ObjectType::PAD, uu_pad, uu_pkg));
```suggestion
            net_to_object_ref[pad.net.uuid].emplace_back(ObjectType::PAD, uu_pad, uu_pkg);
```

2021-10-09 13:40 UTC, carrotIndustries commented on src/imp/imp_board.cpp
> +        net_to_object_ref[plane.net.uuid].emplace_back(ObjectRef(ObjectType::PLANE, uu));
```suggestion
        net_to_object_ref[plane.net.uuid].emplace_back(ObjectType::PLANE, uu);
```

2021-10-10 15:16 UTC, merged